
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Cihat
 */
public class Demo extends javax.swing.JFrame {

  DefaultListModel model;

  /**
   * Creates new form Demo
   */
  public Demo() {
    initComponents();
    model = new DefaultListModel();
    lstStudents.setModel(model);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    lstStudents = new javax.swing.JList<>();
    lblName = new javax.swing.JLabel();
    txtName = new javax.swing.JTextField();
    btnAdd = new javax.swing.JButton();
    btnRemove = new javax.swing.JButton();
    btnRemoveSeleceted = new javax.swing.JButton();
    btnRemoveAll = new javax.swing.JButton();
    lblMessage = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    lstStudents.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lstStudents.setModel(new javax.swing.AbstractListModel<String>() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    jScrollPane1.setViewportView(lstStudents);

    lblName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lblName.setText("Öğrenci Adı: ");

    btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btnAdd.setText("Öğrenci Ekle");
    btnAdd.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAddActionPerformed(evt);
      }
    });

    btnRemove.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btnRemove.setText("Öğrenci Sil");
    btnRemove.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRemoveActionPerformed(evt);
      }
    });

    btnRemoveSeleceted.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btnRemoveSeleceted.setText("Seçili Sil");
    btnRemoveSeleceted.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRemoveSelecetedActionPerformed(evt);
      }
    });

    btnRemoveAll.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btnRemoveAll.setText("Tümünü Sil");
    btnRemoveAll.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRemoveAllActionPerformed(evt);
      }
    });

    lblMessage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(56, 56, 56)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addGroup(layout.createSequentialGroup()
              .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGap(46, 46, 46)
              .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
              .addComponent(lblName)
              .addGap(18, 18, 18)
              .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnRemoveSeleceted, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnRemoveAll, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(26, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(52, 52, 52)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblName))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnAdd)
          .addComponent(btnRemove))
        .addGap(33, 33, 33)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(btnRemoveSeleceted)
            .addGap(18, 18, 18)
            .addComponent(btnRemoveAll)))
        .addGap(43, 43, 43)
        .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(50, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    model.addElement(txtName.getText());
  }//GEN-LAST:event_btnAddActionPerformed

  private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
    model.removeElement(txtName.getText());
  }//GEN-LAST:event_btnRemoveActionPerformed

  private void btnRemoveSelecetedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveSelecetedActionPerformed
    int index = lstStudents.getSelectedIndex();
    if (index != -1) {
      model.removeElementAt(index);
      lblMessage.setText("Seçili Bir Eleman Silindi...");
    } else {
      lblMessage.setText("Seçili Bir Eleman Yoktur.");
    }
  }//GEN-LAST:event_btnRemoveSelecetedActionPerformed

  private void btnRemoveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAllActionPerformed
    int index = lstStudents.getSelectedIndex();
    if (index != -1) {
      model.removeAllElements();
      lblMessage.setText("Tüm Elemanlar Silindi...");
    } else {
      lblMessage.setText("Seçili Bir Eleman Yoktur.");
    }

  }//GEN-LAST:event_btnRemoveAllActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Demo().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAdd;
  private javax.swing.JButton btnRemove;
  private javax.swing.JButton btnRemoveAll;
  private javax.swing.JButton btnRemoveSeleceted;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblMessage;
  private javax.swing.JLabel lblName;
  private javax.swing.JList<String> lstStudents;
  private javax.swing.JTextField txtName;
  // End of variables declaration//GEN-END:variables
}
